language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - cesar.gayo.bravo@alumnos.upm.es
services:
- mysql
script:
- mvn verify
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
- mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=drachodran-github -Dsonar.login=$SONAR